theme: jekyll-theme-minimal
title: Pratyuish homepage
description: This is my professional journey till now, stay tuned for more updates!

Click here to download resume: https://pratyuish.github.io/assets/Pratyuish_Kiran_Fresh_Executive_Resume_2026.pdf

